extractor = dict(
    categories=dict(
        Abuse=["Abuse", 0],
        Arrest=["Arrest", 1],
        Arson=["Arson", 2],
        Assault=["Assault", 3],
        Banner=["Banner", 4],
        Burglary=["Burglary", 5],
        Explosion=["Explosion", 6],
        Fighting=["Fighting", 7],
        Molotof=["MolotovBomb", 8],
        RoadAccidents=["RoadAccidents", 9],
        Robbery=["Robbery", 10],
        Shooting=["Shooting", 11],
        Shoplifting=["Shoplifting", 12],
        Stealing=["Stealing", 13],
        Vandalism=["Vandalism", 14],
        Normal=["Normal", 15]
    ))
